### PR TITLE
Implementation of Interval Tree.

### PR DESCRIPTION
**Pull request by kounkou**
Hey @benstiglitz @niieani @randywallace @masavini @MatthewBregg 

First of all, congratulations for the bash oo framework project.
Here is my little contribution
I am pull this request to introduce the Interval tree to the project.
https://en.wikipedia.org/wiki/Interval_tree
I am planning to implement more functionalities for the Interval tree as well as Unittest once I will feel a bit more
comfortable with it.
Let me know if there is any question.

In the meantime, take care !

### CODE REVIEW

**Comment by kounkou** [comment]
Hey ? @benstiglitz @niieani @randywallace @masavini

**Comment by niieani** [comment]
Hi @kounkou, I wouldn't add it to the core library, as I don't think it belongs there, but I'm happy to put it in the `examples` folder.

**Comment by niieani** [comment]
Hi @kounkou, I wouldn't add it to the core library, as I don't think it belongs there, but I'm happy to put it in the `examples` folder.

**Comment by kounkou** [comment]
@niieani thanks ;-)

**Comment by niieani** [comment]
@kounkou if you want to move it to the `examples` folder in full, I'll merge. Thanks!

**Comment by kounkou** [comment]
Perfect ! 
sorry for the delay, 
please check #79

**Pull request closed without merging**
