### PR TITLE
fix: unicode number for ArrowLeft & ArrowRight

### PR DESCRIPTION
**Pull request by bborysenko**
```
 Testing [Operations on primitives]:
✔ [ OK ] it should make a number and change its value using the setter
✔ [ OK ] it should make basic operations on two arrays
 Completed [Operations on primitives]: Test group completed succesfully 👍
```

With this pull request:

```
▶ Testing [Operations on primitives]:
✔ [ OK ] it should make a number and change its value using the setter
✔ [ OK ] it should make basic operations on two arrays
◀ Completed [Operations on primitives]: Test group completed succesfully 👍
```

### CODE REVIEW

**Comment by niieani** [comment]
These are Powerline arrows (non-unicode), but I'm happy to make this work with non-powerline fonts 👍.


powerline

**Review by niieani — CHANGES_REQUESTED** [review]
Could you make the same change to the alternative `Color.var.sh` too?

**Comment by aadrian** [comment]
> ...but I'm happy to make this work with non-powerline fonts

@niieani  any chance fixing this?

**Comment by niieani** [comment]
Yeah, let's do it. Thanks @bborysenko and @aadrian for the ping.

**Pull request merged**
